apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-dmz-pvc
  namespace: dmz
  labels:
    type: local
spec:
  storageClassName: local-rabbitmq-dmz-storage
  capacity:
    storage: 100M
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/luoji/.orbstack/data/k8s/dmzrabbitmq
